### ISSUE TITLE
Correct `Nr_Libraries` inference (and hence also `Capture_Type`)

### ISSUE THREAD

**Issue by TCLamnidis** [sidora-tools/eager2poseidon#5]
The current implementation of inferring these values from an eager input TSV does not check for uniqueness of library IDs, so a library sequenced over multiple lanes is treated as multiple libraries.

**Comment by stschiff** [comment]
Yeah, we had been deliberately vague on this when we defined this. Needs discussion!

**Comment by stschiff** [comment]
Ah sorry... this is about eager2poseidon. Nevermind my comment then. Good point!
